"""initial schema

Revision ID: c0a9644e189c
Revises: 
Create Date: 2026-05-12 00:34:27.782045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a9644e189c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('angles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('trending', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_angles_type'), 'angles', ['type'], unique=False)
    op.create_table('hooks',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('offer_type', sa.String(length=100), nullable=True),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('trending', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hooks_type'), 'hooks', ['type'], unique=False)
    op.create_table('offers',
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('trending', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_type'), 'offers', ['type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspace_settings',
    sa.Column('workspace_name', sa.String(length=255), nullable=False),
    sa.Column('default_platform', sa.String(length=20), nullable=False),
    sa.Column('confidence_threshold', sa.Integer(), nullable=False),
    sa.Column('auto_analyze', sa.Boolean(), nullable=False),
    sa.Column('review_on_low_conf', sa.Boolean(), nullable=False),
    sa.Column('notif_email', sa.Boolean(), nullable=False),
    sa.Column('notif_in_app', sa.Boolean(), nullable=False),
    sa.Column('notif_review_ready', sa.Boolean(), nullable=False),
    sa.Column('notif_analysis_done', sa.Boolean(), nullable=False),
    sa.Column('fb_ads_api_key', sa.Text(), nullable=True),
    sa.Column('tiktok_ads_api_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefs',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('hook_type', sa.String(length=50), nullable=True),
    sa.Column('angle', sa.String(length=50), nullable=True),
    sa.Column('offer_type', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('key_messages', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('suggested_copy', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('priority_tier', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('niches', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_status'), 'competitors', ['status'], unique=False)
    op.create_table('ads',
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('primary_text', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=100), nullable=True),
    sa.Column('ad_url', sa.Text(), nullable=True),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('is_video', sa.Boolean(), nullable=False),
    sa.Column('ad_library_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('variants', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_competitor_id'), 'ads', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_ads_first_seen'), 'ads', ['first_seen'], unique=False)
    op.create_index(op.f('ix_ads_platform'), 'ads', ['platform'], unique=False)
    op.create_index(op.f('ix_ads_status'), 'ads', ['status'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('objective', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=False),
    sa.Column('brief_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('ad_analyses',
    sa.Column('ad_id', sa.UUID(), nullable=False),
    sa.Column('hook_type', sa.String(length=50), nullable=True),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('angle', sa.String(length=50), nullable=True),
    sa.Column('angle_detail', sa.Text(), nullable=True),
    sa.Column('offer_type', sa.String(length=100), nullable=True),
    sa.Column('offer_value', sa.Text(), nullable=True),
    sa.Column('creative_format', sa.String(length=50), nullable=True),
    sa.Column('product_line', sa.Text(), nullable=True),
    sa.Column('audience_type', sa.Text(), nullable=True),
    sa.Column('usp_detected', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('hook_confidence', sa.Float(), nullable=False),
    sa.Column('angle_confidence', sa.Float(), nullable=False),
    sa.Column('offer_confidence', sa.Float(), nullable=False),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggested_angle', sa.Text(), nullable=True),
    sa.Column('suggested_hook', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_analyses_ad_id'), 'ad_analyses', ['ad_id'], unique=True)
    op.create_index(op.f('ix_ad_analyses_confidence_score'), 'ad_analyses', ['confidence_score'], unique=False)
    op.create_table('review_queue',
    sa.Column('ad_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('reason_label', sa.String(length=100), nullable=True),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_ad_id'), 'review_queue', ['ad_id'], unique=False)
    op.create_index(op.f('ix_review_queue_assigned_to'), 'review_queue', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_review_queue_priority'), 'review_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_priority'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_assigned_to'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_ad_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_ad_analyses_confidence_score'), table_name='ad_analyses')
    op.drop_index(op.f('ix_ad_analyses_ad_id'), table_name='ad_analyses')
    op.drop_table('ad_analyses')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_ads_status'), table_name='ads')
    op.drop_index(op.f('ix_ads_platform'), table_name='ads')
    op.drop_index(op.f('ix_ads_first_seen'), table_name='ads')
    op.drop_index(op.f('ix_ads_competitor_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_competitors_status'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_table('briefs')
    op.drop_table('workspace_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_offers_type'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_hooks_type'), table_name='hooks')
    op.drop_table('hooks')
    op.drop_index(op.f('ix_angles_type'), table_name='angles')
    op.drop_table('angles')
    # ### end Alembic commands ###
