export const creativePerformance = {
  data: [
    {
      id: 'cp1',
      name: 'Fast DTF Transfers',
      format: 'Video',
      length: '15s',
      thumbnail: 'https://picsum.photos/seed/cp1/80/80',
      hook: 'Speed Driven',
      angle: 'Same Day Delivery',
      spend: 8420.50,
      leads: 234,
      cpl: 35.98,
      conversions: 52,
      cpa: 161.93,
      roas: 2.14,
      ctr: 3.8,
      frequency: 2.1,
      status: 'high',
    },
    {
      id: 'cp2',
      name: 'Premium Quality Prints',
      format: 'Image',
      length: '1080×1080',
      thumbnail: 'https://picsum.photos/seed/cp2/80/80',
      hook: 'Quality Focused',
      angle: 'Professional Grade',
      spend: 6210.30,
      leads: 178,
      cpl: 34.89,
      conversions: 41,
      cpa: 151.47,
      roas: 2.28,
      ctr: 4.1,
      frequency: 1.8,
      status: 'high',
    },
    {
      id: 'cp3',
      name: 'Same Day Shipping',
      format: 'Video',
      length: '30s',
      thumbnail: 'https://picsum.photos/seed/cp3/80/80',
      hook: 'Urgency Based',
      angle: 'Fast Fulfillment',
      spend: 5890.40,
      leads: 156,
      cpl: 37.76,
      conversions: 35,
      cpa: 168.30,
      roas: 1.88,
      ctr: 3.2,
      frequency: 2.4,
      status: 'average',
    },
    {
      id: 'cp4',
      name: 'Bundle & Save More',
      format: 'Carousel',
      length: '—',
      thumbnail: 'https://picsum.photos/seed/cp4/80/80',
      hook: 'Value Driven',
      angle: 'Cost Savings',
      spend: 4730.20,
      leads: 132,
      cpl: 35.83,
      conversions: 29,
      cpa: 163.11,
      roas: 1.74,
      ctr: 2.9,
      frequency: 3.1,
      status: 'average',
    },
    {
      id: 'cp5',
      name: 'Vibrant Colors DTF',
      format: 'Image',
      length: '1080×1080',
      thumbnail: 'https://picsum.photos/seed/cp5/80/80',
      hook: 'Aesthetic Appeal',
      angle: 'Visual Quality',
      spend: 3840.10,
      leads: 98,
      cpl: 39.18,
      conversions: 21,
      cpa: 182.86,
      roas: 1.42,
      ctr: 2.6,
      frequency: 3.8,
      status: 'low',
    },
  ],
  total: 428,
}
